language: go

go:
  - 1.13.x

env:
  - IMAGE_NAME=mellanox/sriov-cni-test

    #before_script:
    #- go get github.com/mattn/goveralls

script:
  #- make lint
  - make test-coverage
  #- goveralls -coverprofile=sriov-cni.cover -service=travis-ci
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: docker push $IMAGE_NAME:latest
    on:
      branch: master
  # Push image to Dockerhub on tag
  - provider: script
    skip_cleanup: true
    script: >
      bash -c '
      docker tag $IMAGE_NAME $IMAGE_NAME:$TRAVIS_TAG;
      docker push $IMAGE_NAME:$TRAVIS_TAG'
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
